FROM node:16-alpine AS builder
COPY package.json yarn.lock ./
RUN yarn install

FROM node:16-alpine

EXPOSE 3000

CMD ["node", "app.js"]

WORKDIR /app

COPY --from=builder /node_modules /app/node_modules

COPY app.js ./